import cv2

COMMAND_PI_CAMERA = 'picam'
COMMAND_DEVICE_CAMERA = 'device'

WIDTH = 800
HEIGHT = 600
VIDEO_HEIGHT = 80
CONTROL_HEIGHT = 60
SPECTRUM_HEIGHT = 480 - VIDEO_HEIGHT - CONTROL_HEIGHT
FLAGPOLE_HEIGHT = 10

UPDATE_DELAY = 15

TEXT_OFFSET = 12

FONT = cv2.FONT_HERSHEY_SIMPLEX

GAIN = 5
PEAK_WIDTH = 50
PEAK_THRESHOLD = 20
SAVITZKY_GOLAY_FILTER = 7
HOLD_PEAKS = False
PAUSE = False
