import cv2

COMMAND_PI_CAMERA = 'picam'
COMMAND_DEVICE_CAMERA = 'device'

WIDTH = 800
HEIGHT = 480
VIDEO_HEIGHT = 80
CONTROL_HEIGHT = 60
SPECTRUM_HEIGHT = HEIGHT - VIDEO_HEIGHT - CONTROL_HEIGHT
FLAGPOLE_HEIGHT = 10

UPDATE_DELAY = 15

TEXT_OFFSET = 12

FONT = cv2.FONT_HERSHEY_SIMPLEX
